// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum ResultState {
  success,
  error,
}

class TimeLimitResult {
  TimeLimitResult({
    required this.state,
    required this.message,
  });

  ResultState state;

  String message;

  Object encode() {
    return <Object?>[
      state.index,
      message,
    ];
  }

  static TimeLimitResult decode(Object result) {
    result as List<Object?>;
    return TimeLimitResult(
      state: ResultState.values[result[0]! as int],
      message: result[1]! as String,
    );
  }
}

class UsedApp {
  UsedApp({
    required this.id,
    required this.name,
    required this.minutesUsed,
  });

  String id;

  String name;

  int minutesUsed;

  Object encode() {
    return <Object?>[
      id,
      name,
      minutesUsed,
    ];
  }

  static UsedApp decode(Object result) {
    result as List<Object?>;
    return UsedApp(
      id: result[0]! as String,
      name: result[1]! as String,
      minutesUsed: result[2]! as int,
    );
  }
}

class _AppUsageApiCodec extends StandardMessageCodec {
  const _AppUsageApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is TimeLimitResult) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is UsedApp) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return TimeLimitResult.decode(readValue(buffer)!);
      case 129: 
        return UsedApp.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AppUsageApi {
  /// Constructor for [AppUsageApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppUsageApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : __pigeon_binaryMessenger = binaryMessenger,
        __pigeon_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _AppUsageApiCodec();

  final String __pigeon_messageChannelSuffix;

  Future<String?> getPlatformVersion() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.app_usage.AppUsageApi.getPlatformVersion$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return (__pigeon_replyList[0] as String?);
    }
  }

  Future<List<UsedApp?>> getApps() async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.app_usage.AppUsageApi.getApps$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<UsedApp?>();
    }
  }

  Future<TimeLimitResult> setAppTimeLimit(String appId, int durationInMinutes) async {
    final String __pigeon_channelName = 'dev.flutter.pigeon.app_usage.AppUsageApi.setAppTimeLimit$__pigeon_messageChannelSuffix';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appId, durationInMinutes]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as TimeLimitResult?)!;
    }
  }
}
