// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package dev.dartling.app_usage

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ResultState(val raw: Int) {
  SUCCESS(0),
  ERROR(1);

  companion object {
    fun ofRaw(raw: Int): ResultState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TimeLimitResult (
  val state: ResultState,
  val message: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TimeLimitResult {
      val state = ResultState.ofRaw(list[0] as Int)!!
      val message = list[1] as String
      return TimeLimitResult(state, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      state.raw,
      message,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UsedApp (
  val id: String,
  val name: String,
  val minutesUsed: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): UsedApp {
      val id = list[0] as String
      val name = list[1] as String
      val minutesUsed = list[2].let { if (it is Int) it.toLong() else it as Long }
      return UsedApp(id, name, minutesUsed)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      minutesUsed,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object AppUsageApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TimeLimitResult.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UsedApp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is TimeLimitResult -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is UsedApp -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppUsageApi {
  fun getPlatformVersion(callback: (Result<String?>) -> Unit)
  fun getApps(callback: (Result<List<UsedApp>>) -> Unit)
  fun setAppTimeLimit(appId: String, durationInMinutes: Long, callback: (Result<TimeLimitResult>) -> Unit)

  companion object {
    /** The codec used by AppUsageApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppUsageApiCodec
    }
    /** Sets up an instance of `AppUsageApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: AppUsageApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.app_usage.AppUsageApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformVersion() { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.app_usage.AppUsageApi.getApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getApps() { result: Result<List<UsedApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.app_usage.AppUsageApi.setAppTimeLimit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appIdArg = args[0] as String
            val durationInMinutesArg = args[1].let { if (it is Int) it.toLong() else it as Long }
            api.setAppTimeLimit(appIdArg, durationInMinutesArg) { result: Result<TimeLimitResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
